# Uncomment the following lines to enable the Corne RGB Underglow

CONFIG_ZMK_MOUSE=y
#uncomment below if mouse seems jerky
#CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
#CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
#CONFIG_ZMK_EXT_POWER=n
#ZMK_EXT_POWER=n
CONFIG_ZMK_IDLE_TIMEOUT=1000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
